### ISSUE TITLE
Rashig rings with different collision_shape

### ISSUE THREAD

**Issue by gskillas** [bpartopour/PBG#2]
Hello together,
thank you very much for providing the packed bed generator! With spheres the results are really cool.
I was testing it on openSUSE Leap 15, Blender 2.79 (as provided by the distribution) and tried to produce a Rashig-rings packing. This works with
--------------------------------Start---------------------------------------------------------------------------
all other numerical values being set to default
but fails when changing `collision_shape = 'MESH'`
and re-running. What happens is that there are lots of rings at highly negative position (Z coordinate below -30000) and only a few rashig rings (~10 ) are found in the defined cylinder.

Best regards,

George
\# defining particle type, valid types: 'sphere', 'cylinder', 'Raschig Ring', 'f_point_star', 'three_holes', 'four_holes', 'tri_lobes', 'quadrilobes', 'four_hole_sphere'
Particle_type = 'Raschig Ring'

\#\#Tube dimensions
\# Raduis of the Tube
cyl_radius =6
\#  Length of the Tube
\# Warning! This is not the length of the packing. The packing length depends on number of particles. However, this should be in a safe-side to avoid an overload!
cyl_depth = 100

\#\# Particles Properties
\#Number of Particles
number_of_particle =600
\#Particle radius !! in case of Rashig Ring this is outer radius
particle_radius = 1
\#particle innter radius for extruded geometries
particle_inner_radius = 0.6
\#Particle Length (for cylinders, in case of spheres leave it as default)
particle_length = 3.0

\#\# Rigidbody Properties
\#Collision Shape, valid types: 'MESH', 'CONVEX_HULL', 'SPHERE'
collision_shape = 'CONVEX_HULL'`
.
.
.

----------------------End--------------------------------------------------------------------------------------
all other numerical values being set to default
but fails when changing `collision_shape = 'MESH'`
and re-running. What happens is that there are lots of rings at highly negative position (Z coordinate below -30000) and only a few rashig rings (~10 ) are found in the defined cylinder. How can I deal with this situation?

Best regards,

George

**Comment by bpartopour** [comment]
This is most probably a stability issue. having rings and the tube as mesh object causes instability problems. Please go to the Rigidbody_Generator module, and increase the time step and iteration values, then try the simulation again.
