### ISSUE TITLE
Error running on Mac

### ISSUE THREAD

**Issue by aliannejadi** [bpartopour/PBG#3]
am trying to run the PGB script (https://github.com/bpartopour/PBG) on my Mac but I get the following error:

> $ /Applications/Blender.app/Contents/MacOS/Blender -b --addons textools empty.blend -P PBG.py
> 
> Blender 2.82 (sub 7) (hash 375c7dc4caf4 built 2020-03-12 05:31:51)
> 
> Read prefs: /Users/…/Blender/2.82/config/userpref.blend
> 
> found bundled python: /Applications/Blender.app/Contents/Resources/2.82/python
> 
> ___REgister previews
> 
> … .cavity
> 
> … .position
> 
> … .selection
> 
> … .diffuse
> 
> … .bevel_mask
> 
> … .id_element
> 
> … .ao_legacy
> 
> … .normal_tangent
> 
> … .paint_base
> 
> … .wireframe
> 
> … .normal_object_bevel
> 
> … .dust
> 
> … .displacment
> 
> … .id_material
> 
> … .curvature
> 
> … .ao
> 
> … .normal_tangent_bevel
> 
> … .normal_object
> 
> Read blend: /Users/…/PBG/empty.blend
> 
> Packed bed generator module (v-1.1)
> 
> by B Partopour & AG Dixon†
> 
> Heat and Mass Transfer Lab
> 
> Worcester Polytechnic Institute
> 
> Reference : https://doi.org/10.1016/j.powtec.2017.09.009
> 
> /Users/…/PBG added to system path.
> 
> Welcome to the generator
> 
> Initializing the parameters …
> 
> Filling up the bed…
> 
> Solver iterations per step: 200
> 
> Traceback (most recent call last):
> 
> File “/Users/…/PBG/PBG.py”, line 61, in
> 
> simulation_current_frame = rigidbody_simulation(Particle_type, last_particle_drop_frame)
> 
> File “/Users/…/PBG/Simulator.py”, line 37, in rigidbody_simulation
> 
> part_generation(pellet_key,x_y_range,phi_range,top,vectors)
> 
> File “/Users/…/PBG/Rigidbody_generator.py”, line 49, in part_generation
> 
> location = (x[i],y[i],z[i]))
> 
> File “/Applications/Blender.app/Contents/Resources/2.82/scripts/modules/bpy/ops.py”, line 201, in call
> 
> ret = op_call(self.idname_py(), None, kw)
> 
> TypeError: Converting py args to operator properties: : keyword “size” unrecognized

I installed the latest textools addon and loaded it in terminal but it seems not to make a difference. Can anyone help me with it?

Thanks

**Comment by bpartopour** [comment]
What version of Blender are you using? PBG is no compatible with 2.80, please try 2.79 or older.

**Comment by aliannejadi** [comment]
It worked on version 2.77 thanks.
